### ISSUE TITLE
FamilyDocument.Current doesn't work

### ISSUE THREAD

**Issue by artem-marinin** [erfajo/OrchidForDynamo#189]
Revit: 23.1.1.24
Dynamo Core: 2.16.1.2727
Dynamo Revit: 2.16.1.6510
Orchid: 216.3.0.5797

Hi there!
My aim is to add shared parameters to families. I do it in according to Gavin Crump [YouTube tutorial](https://youtu.be/JdoSnPFqd6E).

I want to use the "FamilyDocument.Current" node, but it doesn't work. A warning appears:
![image](https://user-images.githubusercontent.com/126454788/221523008-88ed4da9-e553-48aa-ad9b-190a0e8a0ae4.png)

Dynamo also alerts that failed to load library "OrchidIB.dll" and failed to load "IFCExporterUIOverride":
![image](https://user-images.githubusercontent.com/126454788/221524301-61ab152a-5943-48d1-9392-afccb5dc0d83.png)

Please, help to fix the "FamilyDocument.Current" node.

Best regards,
Artem

**Comment by erfajo** [comment]
Try to update to the release from today please... 5805
I am affraid the the version you have downloaded was one of them where I made an error...

when I was making some new nodes I made an error, you can follow the process here
https://github.com/erfajo/OrchidForDynamo/issues/184

and here
https://github.com/erfajo/OrchidForDynamo/issues/188

Should be solved by now :-)

**Comment by artem-marinin** [comment]
Hi @erfajo,
Thank you for the quick reply!
I have updated the Orchid to 5805 release.
![image](https://user-images.githubusercontent.com/126454788/221539809-a388fa00-5aa0-433d-b227-3fe125f9bc9f.png)

But the "FamilyDocument.Current" node still doesn't work - the same warning as I attached above (0x00000007/u01 error).
I restarted my PC, created a new family file and a new dynamo file - nothing changes.
Just as extra information, I use Windows 10 Pro, version 22H2, build 19045.2604.
I have learned the issues #184 and #188 you shared, but I didn't find anything which can help in my case.
What could I miss?

Best regards,
Artem

**Comment by erfajo** [comment]
How you are able to catch the 0x00000007/u01 error is strange...

It makes no sense... But I Will try to see if  Windows 10 Pro, version 22H2, build 19045.2604 is supported by the Microsoft.Windows.SDK.Contracts API. If not I am a bit lost...

**Comment by artem-marinin** [comment]
Do I understand you correct, are you going to check/update your source code? Or can I update something on my side?

**Comment by erfajo** [comment]
I need to check on my source code first... It is the first time I have starting using the windows API, so I might have missed something important... But it will take a day or so before I can return to you.

Will it be possible to do a teams meeting or something where I can see what goes on?

**Comment by erfajo** [comment]
thanks, I will return... just for my info, which timezone are we talking about? and I need a mail I can invite.
- I will remove your mail asap I have it, so it cant be misused

**Comment by artem-marinin** [comment]
The most comfortable time for me is between 10 AM and 4 PM Moscow time. If it's not suitable for you, I will try to adjust at your convenience.
My email - aimarinin@yandex.ru

**Comment by erfajo** [comment]
Just one thing, do you have the JSON API installed somehow? I use the version that comes with the Dynamo Nuget package, and for 2.16 I believe it is 13.0.1 (and 8.0.3 for earlier versions of Dynamo). I know that JSON has been an issue before, and I do use JSON files for storing data.
![image](https://user-images.githubusercontent.com/2844374/221610054-776d300a-6fa0-4aeb-aa52-c40984a88d4d.png)

**Comment by erfajo** [comment]
I have now made a beta build, I would like you to test.
I have included a check for json in it, so I can see if that should be the problem... and I have forced a new error code, so if you get that something is really wrong :-S
![image](https://user-images.githubusercontent.com/2844374/221620423-9d9ac9a0-be7e-426d-9c64-5d1626e5f5ae.png)

**Comment by artem-marinin** [comment]
Hi Erik! I have tested the 5805-beta. The error remains. Is it OK that BETA_5805.exe unpacks nothing in C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\2.16\packages? I have this question, because EXE-installers for your previous builds creates "Orchid" folder with files in this path. Now I'm looking for Dynamo Nuget package to install it.
Thanks a lot for your time!

**Comment by erfajo** [comment]
You should not install the nuget package... it is only for developers. But if you have PyRevit it comes with a json that is different than dynamo... or it used to be so... but I dont know it for sure.

**Comment by artem-marinin** [comment]
Thanks for the notification regarding nuget package. I have installed PyRevit, change language on English in Revit and Windows.  The error remains...:(((

**Comment by artem-marinin** [comment]
I have installed the 5806 build. The error remains. Also new notification has appeared:
![image](https://user-images.githubusercontent.com/126454788/221828929-12e6c427-15c4-43ff-8826-77ab74c768a3.png)
But it might be caused by IronPython update, which I did during Clockwork package testing. By the way, the "CurrentFamilyType" node from Clockwork works fine. The similar Orchid node doesn't work as well as other Orchid nodes which reffers to current family or project file. In the same time, for example, the "Culture.Current" node from Orchid works good.

**Comment by artem-marinin** [comment]
I have removed all other packages as you wrote.
![image](https://user-images.githubusercontent.com/126454788/221836463-8cb860c9-39c5-41bb-8ef9-3bbf0668d633.png)
Also I deleted all Addins from AppData\Roaming\Autodesk\Revit\Addins\2023.
The error remains...

**Comment by erfajo** [comment]
and it is with english as language? ... can you send a screendump of the error?

**Comment by artem-marinin** [comment]
Yes, Windows and Revit was swiched on Enlglish language.
Here is the error:
![image](https://user-images.githubusercontent.com/126454788/221850317-0da7938e-72a2-4eff-852d-c20df3bc45f2.png)

I have paths for packages by default
![image](https://user-images.githubusercontent.com/126454788/221849265-a2e00d76-9644-4520-b05b-464c5d25c1dc.png)

![image](https://user-images.githubusercontent.com/126454788/221849502-d39753c3-bdc2-45c7-9686-86e193e4e1e9.png)

![image](https://user-images.githubusercontent.com/126454788/221849591-6c22b040-0407-4216-a125-cd716b5031cb.png)
Here are only dyf files.

**Comment by artem-marinin** [comment]
OK, If you need extra info, let me, please. Tomorrow I will be busy, but I will be able to escape for 30 minutes Teams meeting around 16:10 Moscow time, if you need. Many thanks!

**Comment by erfajo** [comment]
it might be crazy, but I have tested if characters could be something... I made a new betabuild, could you try this out?

**Comment by artem-marinin** [comment]
Hi Erik! I have tested 5807 beta. Nothing news. The same error 0x00000007/00u.

**Comment by erfajo** [comment]
I really dont get it...

In my code it should throw errors for the windows API, for Json, and lastly for Cyrillic (or any other non Latin) letters... end ending with the error code you have sent,I am beginning to reach the end for options... :-S

**Comment by artem-marinin** [comment]
I see it's hard to understand what's the reason. I think I should find other ways to get what I need. Anyway if I find out how to pass by the issue I will write here. If you have new Ideas, let me know please, and I will test them. Thanks a lot to you!

**Comment by erfajo** [comment]
I have uploaded yet another beta build... I hope this one will do it... however, if so it will give me other problems, but then I must deal with them subsequently. -->5808_beta

**Comment by artem-marinin** [comment]
Now I'm out of workplace till night. I'll test it ASAP.

**Comment by erfajo** [comment]
Yesterday another user did report the same error as you, and the 5808_beta seemed to have fixed it, so I have removed it and uploaded new builds… if it still not solves your problem, then please report it asap.

Starting to use the windows API is a challenge, and your error is therefore important for me to fix, by now it is only bypassed. Will it be doable to make further tests where I continue making beta builds well-knowing that these might fail while testing which boundaries I hit?

Otherwise, if everything works I will close this issue, thank you for your report :-)

**Comment by artem-marinin** [comment]
Hej Erik!
Sorry for the long reply, it's a pretty busy week.
I have installed the last build (BETA_5809). Hooooray! It works!!! :) Thank you very much! If you need a help from side, for example, for testing, contact me. I will try to help.

**Comment by erfajo** [comment]
the 5809 build should also work... the 5809_beta is solving some issues with Revit "filters" you can set... but the user who has the problem has now asked a function that can show all filters no matter how complex it is build... this is what I am working on with that beta :-)

**Comment by pbosez** [comment]
Hello there. Same problem with a different node (Document.Current)

Revit: 22.1.30.34
Dynamo: 2.12.1.8246
Orchid: 212.4.0.5812

![DocumentCurrent](https://user-images.githubusercontent.com/94310936/224946234-90a66ab1-55d8-48c8-9154-ea7a9e4d68f4.png)
