### ISSUE TITLE
Revit crashes when I start Dynamo

### ISSUE THREAD

**Issue by Glenn36** [erfajo/OrchidForDynamo#262]
### Operating system
Windows 10.

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 25.0.2.419
Dynamo Revit: 3.0.3.3952
Orchid : Orchid_320_Revit (i cannot see the exact version because Revit crashes when i start Dynamo when Orchid is installed, i installed the latest version, and it still crashes)

Revit crashes when I start Dynamo. I looked on the Autodesk site and it said that it could be caused by corrupting packages. I uninstalled all packages and installed them again, one by one and tested in between. The problem came back when i installed the orchid package. 

I did some further research and the crash can be traced back to this file: "Microsoft.Windows.SDK.NET.dll" When i delete this file i can run Dynamo but the script, further in depth, this node: "Print.CreateSetting" is not working anymore.

**Comment by erfajo** [comment]
without the "Microsoft.Windows.SDK.NET.dll" assembly, my package for sure not work. This is a part of the .Net8.0 solution I need to ensure is on the machine. Most users will not have the Microsft SDK installed, but some might. I am unaware that this should conflict in Dynamo, since I have an Idea that I am the only one using this. But again, if other do the same, then there might be a problem to solve. So please confirm if other of your packages use that assembly or you have it installed in advance.

...or/and maybe you should try to redownload to ensure that there isn't any error... you could try to download the betabuild present these days, new builds are going to be uploaded asap due to a fix I got solved with other users :-)

**Comment by Glenn36** [comment]
I checked the other packages i installed and they don't use the same assambly. And since i use a laptop of the company i work for, i cannot imagine it was installed in advance. 

I already redownload the latest version of your package but the problem still exist.

I asked my colleague to make the latest update of Revit available. Now I'm waiting for the message that I can install this update. I'll keep you posted.

**Comment by erfajo** [comment]
I have the idea that Autodesk also has some issues since they are updating more frequently with major builds due to the transfer from .net framework 4.8 to .Net 8.0. I have had quite a few issues doing the same, so I am very aware to keep up the pace an follow Autodesk as good as possible.

**Comment by Glenn36** [comment]
I don't know,.. i checked but my Windows did not update.

And even more weird,.. i ran Dynamo on 2 of my collegues workstations and everything works just fine. Same Revit and Dynamo version as me. And we all got the same Dynamo package location.

**Comment by erfajo** [comment]
now it begins to get weird!?
your screendump should not indicate any problems... but, could you test if the SDK assembly somehow got "blocked"?
-read the section "Errors coursed by Windows" here --> https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md

**Comment by Glenn36** [comment]
I don't see any reason why windows should block the SDK assembly. I installed the package again manually and unzipped with 7zip., but Revit is still crashing. 

The only thing is: i have no security section in my properties dialog of the SDK assembly file:
![image](https://github.com/user-attachments/assets/64bb5d4a-a077-43c0-879c-695b662e57a6)

**Comment by Glenn36** [comment]
![image](https://github.com/user-attachments/assets/63f518b7-59b6-4427-a1ec-eda391a0fea5)
![image](https://github.com/user-attachments/assets/5506463e-e17b-4073-9a46-8818844ed01b)

So there is a difference in version. But i checked at the workstation of my collegue and he got the exact same windows version as me. And Dynamo works fine there.

**Comment by erfajo** [comment]
Today MS updated a lot of things, both for Windows and Visual Studio, and I noticed that the SDK assembly updated as well.
![image](https://github.com/user-attachments/assets/bf8290ae-2011-419c-b32b-46132f4d36d3)

So I have now uploaded new builds... please try them out :-)

**Comment by Glenn36** [comment]
It seems like your new update resolved the problem. it looks like it all works fine now. 

I'm gonna test my graphs where i used your package. But if i don't post anything in the next 2 days it is probably all working good again.
